# Generated by Django 3.2.9 on 2021-11-23 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_hero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={},
        ),
    ]
